/**
 * The one surface. Everything a human reads on the two doors — `README.md` (built by
 * `scripts/docs.ts`) and `/` (rendered by `src/home.ts` at request time) — comes from here,
 * and here reads only the sources that already drive the build:
 *   version   ← package.json (HYGIENE 19: one version, one place)
 *   tools     ← src/descriptions.ts (verbatim; the connector's own copy)
 *   journeys  ← RECIPES in src/tools/docs.ts (the filled calls the server serves)
 *   copy      ← docs/SURFACE.md (the only hand-written paragraphs)
 *   status    ← /health, read by the page in the browser, never typed here
 * A tool line typed anywhere else is drift; test/surface.test.ts pins equality.
 */
import { VERSION } from "./version";
import { DESCRIPTIONS } from "./descriptions";
import { RECIPES, CEILING_URI } from "./tools/docs";
import surfaceMd from "../docs/SURFACE.md";

export const REPO_URL = "https://github.com/klappy/door43-mcp";
export const CONVENTION = "`klappy/kitchen` `health-code/mcp-server-build-convention.md`";

export interface Surface {
  name: string;
  version: string;
  what: string;
  isNot: string;
  connect: string[];
  tools: Array<{ name: keyof typeof DESCRIPTIONS; line: string }>;
  journeys: Array<{ recipe: string; about: string; args: string; call: string }>;
  law: string;
}

/** Sections of SURFACE.md by `## Heading`; the preamble before the first `##` is dropped. */
export function sections(md: string): Record<string, string> {
  const out: Record<string, string> = {};
  let key: string | null = null;
  for (const line of md.split("\n")) {
    const h = /^## (.+)$/.exec(line);
    if (h) { key = h[1].trim().toLowerCase(); out[key] = ""; continue; }
    if (key) out[key] += line + "\n";
  }
  for (const k of Object.keys(out)) out[k] = out[k].trim();
  return out;
}

const paragraph = (s: string) => s.replace(/\s*\n\s*/g, " ").trim();
const numbered = (s: string) => s.split("\n").map((l) => l.replace(/^\d+\.\s+/, "").trim()).filter(Boolean);

/** A recipe's first call, spelled the way a person would type it into the client. */
export function callText(recipe: string): string {
  const c = RECIPES[recipe].calls[0];
  if ("tool" in c) return `telemetry ${c.sql.replace(/\s+/g, " ").slice(0, 80)}…`;
  const q = c.query ? "?" + Object.entries(c.query).map(([k, v]) => `${k}=${v}`).join("&") : "";
  const f = c.fields?.length ? ` fields:[${c.fields.map((x) => `"${x}"`).join(",")}]` : "";
  return `execute ${c.method} ${c.path}${q}${f}`;
}

/** A recipe's args, spelled `owner* repo* ref=master` (* = required; `=` = default). Empty → `—`. */
export function argsText(recipe: string): string {
  const a = Object.entries(RECIPES[recipe].args).map(([k, v]) => `${k}${v.required ? "*" : ""}${v.default !== undefined ? `=${v.default}` : ""}`);
  return a.length ? a.join(" ") : "—";
}

export function surface(): Surface {
  const s = sections(surfaceMd);
  for (const k of ["what", "is not", "connect"]) if (!s[k]) throw new Error(`docs/SURFACE.md is missing "## ${k}"`);
  return {
    name: "door43-mcp",
    version: VERSION,
    what: paragraph(s["what"]),
    isNot: paragraph(s["is not"]),
    connect: numbered(s["connect"]),
    tools: (Object.keys(DESCRIPTIONS) as Array<keyof typeof DESCRIPTIONS>).map((name) => ({ name, line: DESCRIPTIONS[name] })),
    journeys: Object.entries(RECIPES).map(([recipe, r]) => ({ recipe, about: r.about, args: argsText(recipe), call: callText(recipe) })),
    law: CEILING_URI,
  };
}

/** README.md, whole. Committed output; `npm run docs` writes it, the test proves it. */
export function renderReadme(serverUrl = "https://door43.klappy.dev"): string {
  const s = surface();
  const L: string[] = [];
  L.push(`<!-- generated by scripts/docs.ts from docs/SURFACE.md + the build sources — edit those, then \`npm run docs\`. Hand edits here fail test/surface.test.ts. -->`);
  L.push(`# ${s.name}`, "");
  L.push(`🚪🔐 Door43 (DCS) as an MCP server — log in with your Door43 account; ${s.tools.map((t) => `\`${t.name}\``).join(" · ")}. Three tools, no pasted tokens. ☁️ Cloudflare Workers.`, "");
  L.push(s.what, "");
  L.push(`${s.isNot}`, "");
  L.push(`## Status`, "");
  L.push(`Live at \`${serverUrl}/mcp\` — reads only (v1). The version is \`package.json\` and nothing else spells it; the server prints it at [\`/\`](${serverUrl}/) and in \`docs()\`. Upstream reachability and version: [\`/health\`](${serverUrl}/health). Validated as built: [docs/validation/2026-09-03-v1.md](docs/validation/2026-09-03-v1.md).`, "");
  L.push(`## Connect in three steps`, "");
  L.push("```", `${serverUrl}/mcp`, "```", "");
  s.connect.forEach((c, i) => L.push(`${i + 1}. ${c}`));
  L.push("", `## The three tools`, "");
  L.push(`| Tool | What it does |`, `|---|---|`);
  for (const t of s.tools) L.push(`| \`${t.name}\` | ${t.line} |`);
  L.push("", `Lines are \`src/descriptions.ts\` verbatim — the same text your client shows.`, "");
  L.push(`## Journeys`, "", `Each is a \`docs({recipe, args})\` the server fills for you (\`*\` = required arg, \`=\` = default); the call it returns is shown with its templates. \`execute({recipe, args, dry_run:true})\` prices it first.`, "");
  L.push(`| Recipe | Does | Args | Call |`, `|---|---|---|---|`);
  for (const j of s.journeys) L.push(`| \`${j.recipe}\` | ${j.about} | \`${j.args}\` | \`${j.call}\` |`);
  L.push("", `## Deploy your own`, "", `Fork, register one OAuth app on your DCS host, set three secrets, push. Every step: [docs/DEPLOY.md](docs/DEPLOY.md).`, "");
  L.push(`## Governance`, "", `Governed by \`${s.law}\` and ${CONVENTION}. Tension found → [docs/TENSIONS.md](docs/TENSIONS.md) + an issue tagged per [docs/OWNERS.md](docs/OWNERS.md).`, "");
  L.push(`**Agents start at [AGENTS.md](AGENTS.md).**`, "");
  L.push(`| Read | For |`, `|---|---|`);
  L.push(`| [AGENTS.md](AGENTS.md) | boarding pass — identity, state, contracts, map, journeys |`);
  L.push(`| [docs/PLAN.md](docs/PLAN.md) | gates, owners, observed values — the resume point |`);
  L.push(`| [docs/SPEC.md](docs/SPEC.md) | boundaries, envelope, tool contracts, auth flow |`);
  L.push(`| [docs/PRD.md](docs/PRD.md) | journeys, requirements, acceptance |`);
  L.push(`| [docs/DESIGN.md](docs/DESIGN.md) | agent-facing design principles |`);
  L.push(`| [docs/CHARTER.md](docs/CHARTER.md) | why, who, not-goals |`);
  L.push(`| [docs/DEPLOY.md](docs/DEPLOY.md) | run your own (one human step) |`);
  L.push(`| [docs/SURFACE.md](docs/SURFACE.md) | the hand-written copy behind this README and \`/\` |`);
  L.push(`| [docs/BORROW-EVALUATION.md](docs/BORROW-EVALUATION.md) | 6B: what we borrowed, bent, begot |`);
  L.push(`| [docs/OWNERS.md](docs/OWNERS.md) · [docs/TENSIONS.md](docs/TENSIONS.md) | who decides, what's unresolved |`);
  L.push(`| [docs/SECURITY.md](docs/SECURITY.md) · [docs/TELEMETRY-POLICY.md](docs/TELEMETRY-POLICY.md) | what we hold, what we track |`);
  L.push("", `License: MIT.`, "");
  return L.join("\n");
}
